# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: test-subject-1
description: Fedora KDE Test
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: rpm-ostree
    repos:
      # Starship: This works with Fedora 43 via the version variable
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - starship
      # AMD Vulkan
      - mesa-vulkan-drivers
      - mesa-vulkan-drivers.i686
      - libva-utils
      - vdpauinfo
      # DISK MANAGEMENT ESSENTIALS
      - kde-partitionmanager
      - gparted
      - gnome-disk-utility
      - btrfs-progs
      - smartmontools
      # Gaming Suite
      - vkBasalt
      - mangohud
      - gamemode
      - lutris
      - goverlay
      - gamescope
      # Productivity & Utils
      - ark
      - filelight
      - kfind
      - kcalc
      - kwrite
      - kate
      - fcitx5
      - spectacle
      - kronometer

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - com.valvesoftware.Steam
          - com.heroicgameslauncher.hgl
          - dev.vencord.Vesktop
          - net.davidotek.pupgui2
          - com.vysp3r.ProtonPlus
          - io.github.radiolamp.mangojuice
          - com.github.Matoking.protontricks
          - com.github.qarmin.czkawka
          - io.github.flattool.Warehouse
          - com.github.tchx84.Flatseal

  - type: script
    scripts:
      - |
        #!/bin/bash
        # Set Power Profile to Balanced
        powerprofilesctl set balanced
        # Optimize disk I/O for gaming
        echo mq-deadline > /sys/block/sda/queue/scheduler 2>/dev/null || true
