# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: test-subject-1
description: Fedora 43 KDE + Native Gaming & Management Suite
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - starship
      - mesa-vulkan-drivers
      - mesa-vulkan-drivers.i686
      - libva-utils
      - vdpauinfo
      - kde-partitionmanager 
      - gparted
      - gnome-disk-utility
      - btrfs-progs
      - smartmontools
      - mangohud
      - gamemode
      - lutris
      - goverlay
      - gamescope
      - ark
      - filelight
      - kfind
      - kcalc
      - kwrite
      - kate
      - fcitx5
      - spectacle
      - kronometer

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - org.freedesktop.Platform.VulkanLayer.vkBasalt
          - com.valvesoftware.Steam
          - com.heroicgameslauncher.hgl
          - dev.vencord.Vesktop
          - net.davidotek.pupgui2
          - com.vysp3r.ProtonPlus
          - io.github.radiolamp.mangojuice
          - com.github.Matoking.protontricks
          - com.github.qarmin.czkawka
          - io.github.flattool.Warehouse
          - com.github.tchx84.Flatseal

  # REPLACED THE SCRIPT MODULE WITH THIS SIMPLE RUN COMMAND
  - type: containerfile
    containerfiles:
      - |
        RUN powerprofilesctl set balanced && \
            echo mq-deadline > /sys/block/sda/queue/scheduler 2>/dev/null || true
