# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: test-subject-601
description: Fedora KDE + OGC Kernel + Disk & File Management Suite
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/g/open-gaming-collective/kernel/repo/fedora-%OS_VERSION%/open-gaming-collective-kernel-fedora-%OS_VERSION%.repo
    install:
      # OGC Kernel & AMD Vulkan
      - kernel-ogc
      - mesa-vulkan-drivers
      - mesa-vulkan-drivers.i686
      # DISK MANAGEMENT ESSENTIALS
      - partitionmanager
      - gparted
      - gnome-disk-utility
      - btrfs-progs
      - smartmontools
      # Gaming Suite (RPM versions)
      - vkbasalt
      - mangohud
      - gamemode
      - lutris
      - goverlay
      - gamescope
      # Others
      - ark
      - filelight
      - kfind
      - kcalc
      - kwrite
      - kate
      - gnome-disk-utility
      - fcitx5
      - spectacle
      - kronometer
 
  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          # APPS & GAMING
          - com.valvesoftware.Steam
          - com.heroicgameslauncher.hgl
          - dev.vencord.Vesktop
          - net.davidotek.pupgui2 # ProtonUp-Qt
          - com.vysp3r.ProtonPlus # ProtonPlus
          - io.github.radiolamp.mangojuice # MangoJuice added here
          # FILE MANAGEMENT
          - org.kde.filelight
          - org.kde.ark
          - org.kde.kfind
          - com.github.qarmin.czkawka
          - io.github.radiolamp.mangojuice
          - com.vysp3r.ProtonPlus
          - net.davidotek.pupgui2
          - com.github.Matoking.protontricks
          - io.github.flattool.Warehouse
          - io.github.kolunmi.Bazaar
          - com.ranfdev.DistroShelf
          - com.github.tchx84.Flatseal
          - dev.vencord.Vesktop
          - com.github.qarmin.czkawka
          
  - type: script
    scripts:
      - |
        #!/bin/bash
        # Set Power Profile to Balanced
        powerprofilesctl set balanced
        # Optimize disk I/O for gaming
        echo mq-deadline > /sys/block/sda/queue/scheduler 2>/dev/null || true
